AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secondary Bucket Stack for Secure Document Management System'

Metadata:
  Author:
    Name: Dimitri Vavoulis
    Description: Portfolio Project - Secure Document Management Backend
  ProjectInfo:
    CreatedDate: '2024-08-20'
    Version: '1.0'

Parameters:
  SecondaryBucketPrefix:
    Type: String
    Description: Prefix for the secondary S3 bucket name

Resources:
  SecondaryBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${SecondaryBucketPrefix}-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: 
                Fn::ImportValue: 'KMSStack-SecondaryBucketKeyArn'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: 'secondary-bucket-logs/'

  LoggingBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'sdm-logging-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

Outputs:
  SecondaryBucketName:
    Description: 'Name of the Secondary S3 bucket'
    Value: !Ref SecondaryBucket
  SecondaryBucketArn:
    Description: 'ARN of the Secondary S3 bucket'
    Value: !GetAtt SecondaryBucket.Arn
